
---
{{- if .Values.influxdb.ingress.enabled -}}
{{- $svcPort := 4000 -}}
{{- if and .Values.influxdb.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.influxdb.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.influxdb.ingress.annotations "kubernetes.io/ingress.class" .Values.influxdb.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: monitoring-ingress
  labels:
    {{- include "ozgsec.labels" . | nindent 4 }}
  {{- with .Values.influxdb.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.influxdb.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.influxdb.ingress.className }}
  {{- end }}
  {{- if .Values.influxdb.ingress.tls }}
  tls:
    {{- range .Values.influxdb.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.influxdb.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: {{ $.Release.Name }}-influxdb
                port:
                  number: 8086
    {{- end }}
{{- end }}
---