{{- if not .Values.webFrontend.features.disableDashboard -}} # keycloak is only needed when the dashboard is active
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
type: Opaque
data:
    {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "keycloak") | default dict }}
    {{- $secretData := (get $secretObj "data") | default dict }}

    {{- $dbPassword := (get $secretData "DB_PASSWORD") | default (randAlphaNum 16 | b64enc) }}
    {{- $adminUsername := (get $secretData "ADMIN_USERNAME") | default ("ozgsec" | b64enc) }}
    {{- $adminPass := (get $secretData "ADMIN_PASS") | default (randAlphaNum 16 | b64enc) }}
    {{- $keystorePass := (get $secretData "KEYSTORE_PASS") | default (randAlphaNum 16 | b64enc) }}


    DB_PASSWORD: {{ $dbPassword | quote }}
    ADMIN_USERNAME: {{ $adminUsername | quote }}
    ADMIN_PASS: {{ $adminPass | quote }}
    KEYSTORE_PASS: {{ $keystorePass | quote }}

{{- end }}