{{- if not .Values.webFrontend.features.disableDashboard -}} # keycloak is only needed when the dashboard is active
{{- if .Values.keycloak.ingress.enabled -}}
{{- $svcPort := 3000 -}}
{{- if and .Values.keycloak.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.keycloak.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.keycloak.ingress.annotations "kubernetes.io/ingress.class" .Values.keycloak.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: auth-ingress
  labels:
    {{- include "ozgsec.labels" . | nindent 4 }}
  {{- with .Values.keycloak.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.keycloak.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.keycloak.ingress.className }}
  {{- end }}
  {{- if .Values.keycloak.ingress.tls }}
  tls:
    {{- range .Values.keycloak.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.keycloak.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          # Disable if not needed
          - pathType: Prefix
            path: /
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - pathType: Prefix
            path: /realms/
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - pathType: Prefix
            path: /resources/
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - pathType: Prefix
            path: /robots.txt
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - pathType: Prefix
            path: /js
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
    {{- end }}
{{- end }}
{{- end }}