{{- if .Values.webFrontend.ingress.enabled -}}
{{- $svcPort := 3000 -}}
{{- if and .Values.webFrontend.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.webFrontend.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.webFrontend.ingress.annotations "kubernetes.io/ingress.class" .Values.webFrontend.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: web-frontend-ingress
  labels:
    {{- include "ozgsec.labels" . | nindent 4 }}
  {{- with .Values.webFrontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.webFrontend.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.webFrontend.ingress.className }}
  {{- end }}
  {{- if .Values.webFrontend.ingress.tls }}
  tls:
    {{- range .Values.webFrontend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.webFrontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: web-frontend-service
                port:
                  number: 3000
    {{- end }}
{{- end }}
