---
apiVersion: v1
kind: Secret
metadata:
  name: web-frontend-credentials
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "webFrontend-credentials") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $password := (get $secretData "nextauth-secret") | default (randAlphaNum 32 | b64enc) }}

  nextauth-secret: {{ $password | quote }}
