apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
  labels:
    {{- include "ozgsec.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: web-frontend
